**

!NonaConfig.slnx
!Directory.Build.props
!Directory.Build.targets
!core/
!core/src/
!core/src/**
!libsql/
!libsql/src/
!libsql/src/**

!admin/
!admin/package.json
!admin/package-lock.json
!admin/index.html
!admin/public/
!admin/public/**
!admin/src/
!admin/src/**
!admin/postcss.config.js
!admin/tailwind.config.js
!admin/tsconfig.json
!admin/tsconfig.app.json
!admin/tsconfig.node.json
!admin/vite.config.ts
!admin/.env
!admin/.env.*
