#!/usr/bin/env python3
"""Embed the one shared corpus into platform test sources; --check detects drift."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
corpus = json.dumps(json.loads((root / 'client/qa/contracts/snapshots.json').read_text()), ensure_ascii=False, separators=(',', ':'))
swift = '// Generated by client/qa/generate-contracts.py; edit the shared JSON corpus.\n'
swift += 'enum SharedContracts {\n    static let json = #"""\n' + corpus + '\n"""#\n}\n'
kotlin = '// Generated by client/qa/generate-contracts.py; edit the shared JSON corpus.\npackage com.nonaconfig.client\n\n'
kotlin += 'internal object SharedContracts {\n    const val json = ' + json.dumps(corpus, ensure_ascii=False).replace('$', '\\$') + '\n}\n'
outputs = {'client/swift/Tests/NonaClientTests/SharedContracts.swift': swift,
           'client/kotlin/nona-client/src/test/kotlin/com/nonaconfig/client/SharedContracts.kt': kotlin}
for name, content in outputs.items():
    path = root / name
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'Stale generated contracts: {name}; run python3 client/qa/generate-contracts.py')
    else:
        path.write_text(content)
